### ISSUE TITLE
Issues on install

### ISSUE THREAD

**Issue by tysum7732** [ChristopherDay/Gangster-Legends-V2#10]
Parse error: syntax error, unexpected 'if' (T_IF), expecting identifier (T_STRING) in C:\xampp\htdocs\class\templateRender.php on line 29

I followed all instructions to install and this is the error that is presented to me.

**Comment by tysum7732** [comment]
Hello ?

**Comment by tysum7732** [comment]
Just some further information,

I am using a local xampp setup.

**Comment by tbone99** [comment]
It's your PHP version.  Move up to PHP 7.0.

**Comment by tysum7732** [comment]
Hello,

Thanks I've just purchased a hosting package for a business project so I
shall tinker with your project on the side lines!
