### ISSUE TITLE
Warning: Division by zero

### ISSUE THREAD

**Issue by jimlunsford** [ChristopherDay/Gangster-Legends-V2#12]
I am getting an error:

> Warning: Division by zero in /home/xxx/xxx/class/user.php on line 236

This is using the latest master from GitHub

**Comment by ChristopherDay** [comment]
This was due to incorrect data within the install scripts, i have now fixed these and pushed them live. You could also go into the admin panel and edit the ranks. Once there you will need to defin the rank health.
