### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by jumbojoffer** [ChristopherDay/Gangster-Legends-V2#14]
It has all been set up and seems to atleast be properly connected to my DB. I have tried to login as admin numerous times, but I cannot get that part to work. It only says I've entered the wrong password. I have gone into my DB, under the "users" table and copy-pasted the username and password but to no awail.
Is there something specific I'm missing? And are there any logs I can have a look at somewhere?

**Comment by tbone99** [comment]
Try to register a new user.  Then go into your DB table users and set U_userLevel to 2 and U_status to 1.  You can delete all other users and rename the new user to admin if you want.  Then try to login.  Use admin email address to login.

**Comment by jumbojoffer** [comment]
Tried registering new user. Worked.
Tried logging in. Worked.
Changed new user's userlevel to 2 and logged back into the account. Worked. Is now admin.

One thing i notice is that the password is encrypted in the database. my mistake was trying to login using the encrypted string (which obviously wont work, but i didn't know it was encrypted).

You may not have directly solved my issue, but you made me realize a key part of my issue.
All works good now
Thanks man!

**Comment by ChristopherDay** [comment]
fixed in 2.2.0
