### ISSUE TITLE
Not fixed in 2.2.0 - Re-Opened - HTTP 500 Error when I attempt to Register

### ISSUE THREAD

**Issue by jhughes94** [ChristopherDay/Gangster-Legends-V2#17]
When I click on Register, it gives me a HTTP 500 error, is anyone able to assist?

**Comment by ChristopherDay** [comment]
are you using version 2.2.0?

**Comment by jhughes94** [comment]
I am using 2.2.0, when I enter the credentials, and then register, it goes to HTTP 500 error, quite baffles by it tbh

**Comment by jhughes94** [comment]
Baffled *

**Comment by ChristopherDay** [comment]
What PHP version are you using and what server?

**Comment by ChristopherDay** [comment]
`ALTER TABLE users CHANGE U_password U_password VARCHAR(255) NOT NULL DEFAULT '';`

put that into phpmyadmin, ive made  aversion 2.2.1 with this fix
