### ISSUE TITLE
Admin - Adding a new rank

### ISSUE THREAD

**Issue by jhughes94** [ChristopherDay/Gangster-Legends-V2#18]
Thank you for fixing the Register issue, just thought that I would play about with the game and have found out when I attempt to Add a new Rank in the admin control panel, it goes to a blank page when I attempt to submit it.

Also, as a request, is there a way we could get a Forgot Password link to allow people to reset their password?

**Comment by ChristopherDay** [comment]
Tested in latest version and it works.
