### ISSUE TITLE
Admin Panel

### ISSUE THREAD

**Issue by CollinsCoding** [ChristopherDay/Gangster-Legends-V2#2]
I'm not exactly sure how I can access an administration panel on my site? I've finished all the steps and it says you've programmed a new admin panel. How would one access this?

**Comment by ChristopherDay** [comment]
I have recently picked up development of this project again. In the current Master branch i have started work on the admin panel. Currently it only supports crimes but i will be adding features to it soon.

To view the admin panel you will need to run the following SQL in your DB admin tool (eg. phpMyAdmin ) `UPDATE users SET U_userLevel = 2 WHERE U_id = {id}` making sure you replace `{id}` WITH your admin user ID
