### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by vizubo** [ChristopherDay/Gangster-Legends-V2#21]
Getting error 500 on Jail and few other pages debug error now displays:

> 
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'mobdon_g4m3.userStats.US_rank' which is not in SELECT list; this is incompatible with DISTINCT' in /home/mobdon/public_html/modules/installed/jail/jail.inc.php:59 Stack trace: #0 /home/mobdon/public_html/modules/installed/jail/jail.inc.php(59): PDOStatement->execute() #1 /home/mobdon/public_html/modules/installed/jail/jail.inc.php(154): jail->getJailUsers() #2 /home/mobdon/public_html/class/module.php(29): jail->constructModule() #3 /home/mobdon/public_html/class/page.php(86): module->__construct() #4 /home/mobdon/public_html/class/page.php(35): page->load('jail') #5 /home/mobdon/public_html/init.php(61): page->loadPage('jail') #6 /home/mobdon/public_html/index.php(4): require('/home/mobdon/pu...') #7 {main} thrown in /home/mobdon/public_html/modules/installed/jail/jail.inc.php on line 59

**Comment by ChristopherDay** [comment]
can you try the latest commit

**Comment by ChristopherDay** [comment]
This has been fixed, the changes are in the master branch.
