### ISSUE TITLE
Gangs are not working

### ISSUE THREAD

**Issue by MrCyjaneK** [ChristopherDay/Gangster-Legends-V2#22]
After clicking on gang 404 Page Not Found module loads, also there is blank menu "Gangs". Is this feature planned to be added/fixed or it is removed?

**Comment by ChristopherDay** [comment]
Gangs were never supposed to be included in the core of GL V2, but as a paid module. You can find this @ http://glscript.cdcoding.com/market.php?action=view&view=1
