### ISSUE TITLE
Logout issues

### ISSUE THREAD

**Issue by kieran268uk** [ChristopherDay/Gangster-Legends-V2#23]
There was an error!
File: /class/page.php
Line: 251
Error: Cannot modify header information - headers already sent by (output started at /themes/default/loggedin.php:1)
Type: E_ALL

**Comment by ChristopherDay** [comment]
what version of GLv2 are you using? I have tested on the master branch and cant replicate this.

**Comment by kieran268uk** [comment]
I downloaded the latest and this is working now.
