### ISSUE TITLE
forgotPassword.inc.php

### ISSUE THREAD

**Issue by tbone99** [ChristopherDay/Gangster-Legends-V2#24]
forgotPassword.inc.php throws a fatal error on Line 31 when I test it.

**Comment by ChristopherDay** [comment]
I have tested the latest version and it works, what error did you get?

**Comment by tbone99** [comment]
It was " Fatal error: Uncaught Error: Call to undefined method PDO::select() ".  I'll try the latest version too and let you know if it comes back.

**Comment by tbone99** [comment]
It works as intended in the latest version.  

The only thing I notice is $_SERVER["HTTP_ORIGIN"] . $_SERVER["SCRIPT_NAME"] does not work in all browsers.
