### ISSUE TITLE
Warning: unlink(../install): Operation not permitted

### ISSUE THREAD

**Issue by marktopper** [ChristopherDay/Gangster-Legends-V2#27]
Hi @ChristopherDay.

As an addition to #26, the next step "Remove installer" fails with the following error.

```
Warning: unlink(../install): Operation not permitted in /Users/mark/Sites/gang/install/step/4.php on line 14
```

**Comment by marktopper** [comment]
This can be due to permissions on the machine, I think this should be changed into a notice, for after the completion, that in case that it could not be deleted, the user should delete the folder themself. Instead of now, where it locks you in a position where you cannot complete the installation script, and deleting the install folder manually will make the button throw a 404 page since the installer will no longer work after that.

**Comment by ChristopherDay** [comment]
This is due to unlink() only working on a file not a directory, i have pushed a fix to the master branch, waiting on release
