### ISSUE TITLE
Characters encoding errors v2.1

### ISSUE THREAD

**Issue by tyupika93** [ChristopherDay/Gangster-Legends-V2#3]
If I'm translating some pages in Hungarian into characters encoding errors. For example, the Crimes menu
Character encoding of database and tables utf-8. I checked and the files got such a character encoding utf-8
![encoding](https://user-images.githubusercontent.com/35248010/45996113-41ba6a80-c09b-11e8-9b74-8b240a079ca3.png)

**Comment by ChristopherDay** [comment]
In the next release all tables will be built using UTF-8 rather then latin1. Because of this GLV2 will now require MySQL version 5.5 or higher
