### ISSUE TITLE
User Login Check

### ISSUE THREAD

**Issue by LukeLyons** [ChristopherDay/Gangster-Legends-V2#36]
i have noticed that pages like Login, Register, Forgot Password are still accessible to users even if they are loggedin i would recommend maybe adding 
`
if(isset($this->user->loggedin)){
	header("Location:?page=" . $this->page->landingPage);
	exit;
}
`
in each of the construct functions to make sure it is checked.

**Comment by uaktags** [comment]
I think this is solved by #52
