### ISSUE TITLE
Undefined Action causes game to break.

### ISSUE THREAD

**Issue by LukeLyons** [ChristopherDay/Gangster-Legends-V2#38]
if an action on any page is undefined it breaks the whole game layout. the problem is with the method_exists when loading the action, if its undefined it returns nothing and if you change to return a 404 page. admin modules no longer work as this runs on a different loader to the main files.

**Comment by uaktags** [comment]
tried with ?page=crimes&action=&crime=1 and ?page=crimes&crime=1 to no ill effect. Any particular pages?
