### ISSUE TITLE
module class

### ISSUE THREAD

**Issue by ChristopherDay** [ChristopherDay/Gangster-Legends-V2#49]
include the module class in inti.php not page.php

**Comment by uaktags** [comment]
page only contains the page class, not a module class. I'm assuming that you're referring to the loadModuleMetaData function, which is provided by the page class. There's no reason to put this logic into the init though, that I can tell. Any reason you'd suggest this?

**Comment by ChristopherDay** [comment]
This ticket was not very clear what i want to do is move this line out of page.php and move it into init.php

https://github.com/ChristopherDay/Gangster-Legends-V2/blob/master/class/page.php#L104

**Comment by ChristopherDay** [comment]
This would allow you to use the Module class in a *.hooks.php file before the module has run

**Comment by agscs** [comment]
will this be for the mods classes??
e.g: home.class.php

**Comment by ChristopherDay** [comment]
No you will be able to make a class within module.hooks.php then you can use it within code i.e.

`module.hooks.php`
```php
<?php
    class item extends module {
        function getItem() {
                $this->db->select(...);
                $this->user->newNotification($this->page->buildElement("notificationText"));
        }
    }

```

Its basically a nicer way to get `$this->db` etc ... in custom classes

**Comment by agscs** [comment]
oh this even better, i realy like it

**Comment by KyleMassacre** [comment]
I know this is pretty stale but what about doing something like a macro for the module class?
```php
// *.hook.php:
module::macro('getItem', function($id) {
    $item = new Item($id);
    return $item->getItem();
})

// *.inc.php:
$item = $this->getItem(1);
```

If you've seen "my" modules, you would probably know why I bring this up.
