### ISSUE TITLE
how to activate the sending of forgotten password?

### ISSUE THREAD

**Issue by GalackQSM** [ChristopherDay/Gangster-Legends-V2#59]
When I test to forget my password, he tells me that he sent a link to change my password, my in my mailbox I do not receive anything

**Comment by ChristopherDay** [comment]
This is usually a problem with the web hosting configuration, what host do you use?

**Comment by GalackQSM** [comment]
https://inulogic.fr

**Comment by ChristopherDay** [comment]
Can you contact them and explain that the mail() function isnt working, you can also check your spam folder?
