### ISSUE TITLE
Error after install regarding nbbc.php

### ISSUE THREAD

**Issue by RecoStar** [ChristopherDay/Gangster-Legends-V2#71]
After a fresh install of GL 2.4.1 I am getting the following error:

`There was an error!
File: /home/galactic/public_html/class/nbbc.php
Line: 155
Error: Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, null given in /home/galactic/public_html/class/nbbc.php:155 Stack trace: #0 /home/galactic/public_html/class/nbbc.php(1953): BBCodeLexer->NextToken() #1 /home/galactic/public_html/class/pageElement.php(56): BBCode->Parse('GL v2 successfu...') #2 /home/galactic/public_html/class/pageElement.php(69): pageElement->convertBBCodeToHTML('GL v2 successfu...') #3 [internal function]: pageElement->{closure}(Object(Handlebars\Template), Object(Handlebars\Context), 'text', '') #4 /home/galactic/public_html/class/Handlebars/Template.php(255): call_user_func_array(Object(Closure), Array) #5 /home/galactic/public_html/class/Handlebars/Template.php(148): Handlebars\Template->section(Object(Handlebars\Context), Array) #6 /home/galactic/public_html/class/Handlebars/Helpers.php(298): Handlebars\Template->render(Object(Handlebars\Context)) #7 [internal function]: Handlebars\Helpers->helperEach(Object(Handlebars\Template), Object(Handlebars\Context), 'news', '\n ...') #8 /home/galactic/public_html/class/Handlebars/Template.php(255): call_user_func_array(Array, Array) #9 /home/galactic/public_html/class/Handlebars/Template.php(148): Handlebars\Template->section(Object(Handlebars\Context), Array) #10 /home/galactic/public_html/class/Handlebars/Handlebars.php(180): Handlebars\Template->render(Object(Handlebars\Context)) #11 /home/galactic/public_html/class/pageElement.php(91): Handlebars\Handlebars->render('\n\n <...', Array) #12 /home/galactic/public_html/class/pageElement.php(141): pageElement->templateToHTML('\n\n <...', Array) #13 /home/galactic/public_html/class/page.php(346): pageElement->parse() #14 /home/galactic/public_html/modules/installed/loggedin/loggedin.inc.php(31): page->buildElement('newsArticle', Array) #15 /home/galactic/public_html/class/module.php(30): loggedin->constructModule() #16 /home/galactic/public_html/class/page.php(144): module->__construct() #17 /home/galactic/public_html/class/page.php(58): page->load('loggedin') #18 /home/galactic/public_html/init.php(86): page->loadPage('loggedin') #19 /home/galactic/public_html/index.php(5): require('/home/galactic/...') #20 {main} thrown
Type: E_RECOVERABLE_ERROR`

**Comment by RecoStar** [comment]
Fixed by reverting back to PHP 7.2

**Comment by ChristopherDay** [comment]
In 2.5 nbbc will support php 7 and 8
