### ISSUE TITLE
Error with Handlebars in usePoints

### ISSUE THREAD

**Issue by RecoStar** [ChristopherDay/Gangster-Legends-V2#72]
Found an error in usePoints page regarding Handlebars:

`There was an error!
File: /home/galactic/public_html/class/Handlebars/Template.php
Line: 395
Error: number_format() expects parameter 1 to be float, string given
Type: E_RECOVERABLE_ERROR`

**Comment by ChristopherDay** [comment]
This is a gl premium bug, this will be fixed in the next release please email me cheis@cdcoding.com if you need the fix asap
