### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Round' not found

### ISSUE THREAD

**Issue by h1x0r1** [ChristopherDay/Gangster-Legends-V2#75]
Fatal error: Uncaught Error: Class 'Round' not found in /var/www/html/Gangster-Legends-V2/class/user.php:166 Stack trace: #0 /var/www/html/Gangster-Legends-V2/install/step/3.php(25): user->makeUser('user1', 'email@email.com', 'password') #1 /var/www/html/Gangster-Legends-V2/install/index.php(68): include('/var/www/html/G...') #2 {main} thrown in /var/www/html/Gangster-Legends-V2/class/user.php on line 166

In 3 step i get this fatal error. Any ideas ?

**Comment by ChristopherDay** [comment]
can you try the last commit i just pushed 

https://github.com/ChristopherDay/Gangster-Legends-V2/commit/63882b4408d872f03aa361e14fd944f10c989bdd
